name:         Shpadoinkle-template
license:      BSD3
license-file: LICENSE
version:      0.0.0.1
author:       Isaac Shapira
maintainer:   fresheyeball@protonmail.com
category:     Web
build-type:   Simple
synopsis:     Read standard file formats into Shpadoinkle with Template Haskell
description:
  This package provides TH functions to read files at compile time and embed them
  into Shpadoinkle views.


ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
    - -fwarn-incomplete-uni-patterns
    - -fwarn-tabs
    - -fwarn-incomplete-record-updates
    - -fwarn-identities


extra-source-files:
  - README.md
  - CHANGELOG.md


dependencies:
    - base >= 4.12.0 && < 4.16
    - text >= 1.2.3 && < 1.3
    - template-haskell
    - html-parse

    - Shpadoinkle
    - Shpadoinkle-backend-static


library:
  exposed-modules:
   - Shpadoinkle.Template.TH
   - Shpadoinkle.Template
  other-modules: []
  source-dirs: .


tests:
  sample:
    main: Test.hs
    source-dirs: .
    dependencies:
      - Shpadoinkle-template
      - file-embed


git: https://gitlab.com/platonic/shpadoinkle.git
