stages:
  - build

#build-844-ghc:
#  stage: build
#  script:
#  - nix-build --argstr compiler ghc844 --fallback
#  - rm -r result*
#  artifacts:
#    untracked: true
#
#build-844-ghcjs:
#  stage: build
#  script:
#  - nix-build --argstr compiler ghc844 --arg isJS true --fallback
#  - rm -r result*
#  artifacts:
#    untracked: true

build-864-ghc:
  stage: build
  script:
  - nix-build --argstr compiler ghc864 --fallback
  - rm -r result*
  artifacts:
    untracked: true

build-864-ghcjs:
  stage: build
  script:
  - nix-build --argstr compiler ghc864 --arg isJS true --fallback
  - rm -r result*
  artifacts:
    untracked: true

# shell-844-ghc:
#   stage: build
#   script:
#   - nix-shell --argstr compiler ghc844 --command "echo works" --fallback
#   artifacts:
#     untracked: true
#
# shell-844-ghcjs:
#   stage: build
#   script:
#   - nix-shell --argstr compiler ghc844 --arg isJS true --command "echo works" --fallback
#   artifacts:
#     untracked: true

shell-864-ghc:
  stage: build
  script:
  - nix-shell --argstr compiler ghc864 --command "echo works" --fallback
  artifacts:
    untracked: true

shell-864-ghcjs:
  stage: build
  script:
  - nix-shell --argstr compiler ghc864 --arg isJS true --command "echo works" --fallback
  artifacts:
    untracked: true

# test-864-ghc:
#   stage: test
#   script:
#   - nix-build test.nix --argstr compiler ghc864 --arg isJS false --fallback
#   - rm -r result
#   artifacts:
#     untracked: true
#
# test-864-ghcjs:
#   stage: test
#   script:
#   - nix-build test.nix --argstr compiler ghc864 --arg isJS true --fallback
#   - rm -r result
#   artifacts:
#     untracked: true

pages:
  stage: build
  script:
  - nix-build --arg isJS true -A Shpadoinkle-examples --fallback
  - mkdir -p public/todomvc

  - cp -r result/bin/todomvc.jsexe/* public/todomvc
  - rm -r result

  - nix-build docs --fallback

  - cp -r result/* public
  - rm -r result
  artifacts:
    paths:
    - public

  only:
  - master


cachix:
  stage: build
  script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix authtoken $AUTHTOKEN
  - nix-build --arg isJS true                              | cachix push shpadoinkle
  - nix-build --arg isJS false                             | cachix push shpadoinkle
  - nix-build --arg isJS true  -A Shpadoinkle-examples.env | cachix push shpadoinkle
  - nix-build --arg isJS false -A Shpadoinkle-examples.env | cachix push shpadoinkle
  - nix-build --arg isJS true  -A Shpadoinkle-tests.env    | cachix push shpadoinkle
  - nix-build --arg isJS false -A Shpadoinkle-tests.env    | cachix push shpadoinkle
  only:
  - master
