stages:
  - build
  - test

# build-844-ghc:
#   stage: build
#   script:
#   - nix-build --argstr compiler ghc844 --fallback
#   - rm -r result*
#   artifacts:
#     untracked: true
#
# build-844-ghcjs:
#   stage: build
#   script:
#   - nix-build --argstr compiler ghc844 --arg isJS true --fallback
#   - rm -r result*
#   artifacts:
#     untracked: true
#
# shell-844-ghc:
#   stage: build
#   script:
#   - NIXPKGS_ALLOW_UNFREE=1 nix-shell --argstr compiler ghc844 --command "echo works" --fallback
#   artifacts:
#     untracked: true
#
# shell-844-ghcjs:
#   stage: build
#   script:
#   - NIXPKGS_ALLOW_UNFREE=1 nix-shell --argstr compiler ghc844 --arg isJS true --command "echo works" --fallback
#   artifacts:
#     untracked: true

build-864-ghc:
  stage: build
  script:
  - export NIXPKGS_ALLOW_UNFREE=1
  - export NIXPKGS_ALLOW_BROKEN=1
  - nix-build --argstr compiler ghc864 --fallback
  - rm -r result*
  artifacts:
    untracked: true

build-864-ghcjs:
  stage: build
  script:
  - export NIXPKGS_ALLOW_UNFREE=1
  - export NIXPKGS_ALLOW_BROKEN=1
  - nix-build --argstr compiler ghc864 --arg isJS true --fallback
  - rm -r result*
  artifacts:
    untracked: true

shell-864-ghc:
  stage: build
  script:
  - export NIXPKGS_ALLOW_UNFREE=1
  - export NIXPKGS_ALLOW_BROKEN=1
  - nix-shell --argstr compiler ghc864 --command "echo works" --fallback
  artifacts:
    untracked: true

shell-864-ghcjs:
  stage: build
  script:
  - export NIXPKGS_ALLOW_UNFREE=1
  - export NIXPKGS_ALLOW_BROKEN=1
  - nix-shell --argstr compiler ghc864 --arg isJS true --command "echo works" --fallback
  artifacts:
    untracked: true

test-864-ghc:
  stage: test
  script:
  - export NIXPKGS_ALLOW_UNFREE=1
  - export NIXPKGS_ALLOW_BROKEN=1
  - nix-build test.nix --argstr compiler ghc864 --arg isJS false --fallback
  - rm -r result
  artifacts:
    untracked: true

test-864-ghcjs:
  stage: test
  script:
  - export NIXPKGS_ALLOW_UNFREE=1
  - export NIXPKGS_ALLOW_BROKEN=1
  - nix-build test.nix --argstr compiler ghc864 --arg isJS true --fallback
  - rm -r result
  artifacts:
    untracked: true

pages:
  stage: build
  script:
  - export NIXPKGS_ALLOW_UNFREE=1
  - export NIXPKGS_ALLOW_BROKEN=1
  - nix-build --arg isJS true -A Shpadoinkle-examples --fallback
  - mkdir public
  - cp -r result/bin/todomvc.jsexe/* public
  artifacts:
    paths:
    - public

  only:
  - master

