stages:
  - Linux Build
  - Darwin Build
  - Linux Shell
  - Darwin Shell
  - Documentation
  - Deploy

Build with GHC 8.6.5 on Linux:
  stage: Linux Build
  needs: []
  script:
  - nix-build --argstr compiler ghc865 --fallback

Build with GHCJS 8.6 on Linux:
  stage: Linux Build
  needs: []
  script:
  - nix-build --argstr compiler ghc865 --arg isJS true --fallback

Build with GHC 8.6.5 on Darwin:
  stage: Darwin Build
  needs: []
  script:
  - nix-build --argstr compiler ghc865 --argstr system x86_64-darwin --fallback

Build with GHCJS 8.6 on Darwin:
  stage: Darwin Build
  needs: []
  script:
  - nix-build --argstr compiler ghc865 --argstr system x86_64-darwin --arg isJS true --fallback

Shell for GHC 8.6.5 on Linux:
  stage: Linux Shell
  needs:
  - Build with GHC 8.6.5 on Linux
  script:
  - nix-build -A Shpadoinkle-examples.env --argstr compiler ghc865 --fallback

Shell for GHCJS 8.6 on Linux:
  stage: Linux Shell
  needs:
  - Build with GHCJS 8.6 on Linux
  script:
  - nix-build -A Shpadoinkle-examples.env --argstr compiler ghc865 --arg isJS true --fallback

Shell for GHC 8.6.5 on Darwin:
  stage: Darwin Shell
  needs:
  - Build with GHC 8.6.5 on Darwin
  script:
  - nix-build -A Shpadoinkle-examples.env --argstr compiler ghc865 --argstr system x86_64-darwin --fallback

Shell for GHCJS 8.6 on Darwin:
  stage: Darwin Shell
  needs:
  - Build with GHCJS 8.6 on Darwin
  script:
  - nix-build -A Shpadoinkle-examples.env --argstr compiler ghc865 --argstr system x86_64-darwin --arg isJS true --fallback

# test-865-ghc:
#   stage: test
#   script:
#   - nix-build test.nix --argstr compiler ghc865 --arg isJS false --fallback
#   - rm -r result
#   artifacts:
#     untracked: true
#
# test-865-ghcjs:
#   stage: test
#   script:
#   - nix-build test.nix --argstr compiler ghc865 --arg isJS true --fallback
#   - rm -r result
#   artifacts:
#     untracked: true

pages:
  stage: Documentation
  needs:
  - Build for GHCJS 8.6 on Linux
  script:
  - ./nix/build-pages.sh
  artifacts:
    paths:
    - public
  only:
  - master
  - docs


Upload to Cachix:
  stage: Deploy
  needs:
  - Build with GHC 8.6.5 on Linux
  - Build with GHCJS 8.6 on Linux
  - Build with GHC 8.6.5 on Darwin
  - Build with GHCJS 8.6 on Darwin
  - Shell for GHC 8.6.5 on Linux
  - Shell for GHCJS 8.6 on Linux
  - Shell for GHC 8.6.5 on Darwin
  - Shell for GHCJS 8.6 on Darwin
  script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix authtoken $AUTHTOKEN
  - ./nix/cachix.sh
  only:
  - master
