stages:
  - build

build-864-ghc:
  stage: build
  script:
  - nix-build --argstr compiler ghc864 --fallback

build-864-ghcjs:
  stage: build
  script:
  - nix-build --argstr compiler ghc864 --arg isJS true --fallback

shell-864-ghc:
  stage: build
  script:
  - nix-shell --argstr compiler ghc864 --command "echo works" --fallback

shell-864-ghcjs:
  stage: build
  script:
  - nix-shell --argstr compiler ghc864 --arg isJS true --command "echo works" --fallback

antora:
  stage: build
  script:
  - nix-build docs --fallback

# test-864-ghc:
#   stage: test
#   script:
#   - nix-build test.nix --argstr compiler ghc864 --arg isJS false --fallback
#   - rm -r result
#   artifacts:
#     untracked: true
#
# test-864-ghcjs:
#   stage: test
#   script:
#   - nix-build test.nix --argstr compiler ghc864 --arg isJS true --fallback
#   - rm -r result
#   artifacts:
#     untracked: true

pages:
  stage: build
  script:
  - nix-build --arg isJS true -A Shpadoinkle-examples --fallback

  - mkdir -p public/examples
  - cp -r result/bin/*.jsexe public/examples
  - rm result*

  - nix-build docs --fallback

  - cp -r result/* public
  - ./fish.sh
  - chmod -R 755 public/*
  artifacts:
    paths:
    - public
  only:
  - master
  - docs


cachix:
  stage: build
  script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix authtoken $AUTHTOKEN
  - nix-build --arg isJS true                              | cachix push shpadoinkle
  - nix-build --arg isJS false                             | cachix push shpadoinkle
  - nix-build --arg isJS true  -A Shpadoinkle-examples.env | cachix push shpadoinkle
  - nix-build --arg isJS false -A Shpadoinkle-examples.env | cachix push shpadoinkle
  - nix-build --arg isJS true  -A Shpadoinkle-tests.env    | cachix push shpadoinkle
  - nix-build --arg isJS false -A Shpadoinkle-tests.env    | cachix push shpadoinkle
  only:
  - master
