stages:
  - Linux Build
  - Darwin Build
  - Linux Shell
  - Darwin Shell
  - Antora Documentation
  - Push Artifacts

Build with GHC 8.6.5 on Linux:
  stage: Linux Build
  needs: []
  script:
  - nix-build --argstr compiler ghc865 --fallback

Build with GHCJS 8.6 on Linux:
  stage: Linux Build
  needs: []
  script:
  - nix-build --argstr compiler ghc865 --arg isJS true --fallback

Build with GHC 8.6.5 on Darwin:
  stage: Darwin Build
  needs: []
  script:
  - nix-build --argstr compiler ghc865 --argstr system x86_64-darwin --fallback

Build with GHCJS 8.6 on Darwin:
  stage: Darwin Build
  needs: []
  script:
  - nix-build --argstr compiler ghc865 --argstr system x86_64-darwin --arg isJS true --fallback

Shell for GHC 8.6.5 on Linux:
  stage: Linux Shell
  needs:
  - Build with GHC 8.6.5 on Linux
  script:
  - nix-build -A Shpadoinkle-examples.env --argstr compiler ghc865 --fallback

Shell for GHCJS 8.6 on Linux:
  stage: Linux Shell
  needs:
  - Build with GHCJS 8.6 on Linux
  script:
  - nix-build -A Shpadoinkle-examples.env --argstr compiler ghc865 --arg isJS true --fallback

Shell for GHC 8.6.5 on Darwin:
  stage: Darwin Shell
  needs:
  - Build with GHC 8.6.5 on Darwin
  script:
  - nix-build -A Shpadoinkle-examples.env --argstr compiler ghc865 --argstr system x86_64-darwin --fallback

Shell for GHCJS 8.6 on Darwin:
  stage: Darwin Shell
  needs:
  - Build with GHCJS 8.6 on Darwin
  script:
  - nix-build -A Shpadoinkle-examples.env --argstr compiler ghc865 --argstr system x86_64-darwin --arg isJS true --fallback

Build Antora:
  stage: Antora Documentation
  needs: []
  script:
  - nix-build docs --fallback

# test-865-ghc:
#   stage: test
#   script:
#   - nix-build test.nix --argstr compiler ghc865 --arg isJS false --fallback
#   - rm -r result
#   artifacts:
#     untracked: true
#
# test-865-ghcjs:
#   stage: test
#   script:
#   - nix-build test.nix --argstr compiler ghc865 --arg isJS true --fallback
#   - rm -r result
#   artifacts:
#     untracked: true

pages:
  stage: Push Artifacts
  needs:
  - Build Antora
  - Shell for GHCJS 8.6 on Linux
  script:
  - nix-build --arg isJS true -A Shpadoinkle-examples --fallback

  - mkdir -p public/examples
  - cp -r result/bin/*.jsexe public/examples
  - rm result*

  - nix-build docs --fallback

  - cp -r result/* public
  - ./fish.sh
  - chmod -R 755 public/*
  artifacts:
    paths:
    - public
  only:
  - master
  - docs


Upload to Cachix:
  stage: Push Artifacts
  needs:
  - Build with GHC 8.6.5 on Linux
  - Build with GHCJS 8.6 on Linux
  - Build with GHC 8.6.5 on Darwin
  - Build with GHCJS 8.6 on Darwin
  - Shell for GHC 8.6.5 on Linux
  - Shell for GHCJS 8.6 on Linux
  - Shell for GHC 8.6.5 on Darwin
  - Shell for GHCJS 8.6 on Darwin
  script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix authtoken $AUTHTOKEN
  - ./cachix.sh
  only:
  - master
