stages:
  - build
  - test
  - push

#build-844-ghc:
#  stage: build
#  script:
#  - export NIXPKGS_ALLOW_UNFREE=1
#  - export NIXPKGS_ALLOW_BROKEN=1
#  - nix-build --argstr compiler ghc844 --fallback
#  - rm -r result*
#  artifacts:
#    untracked: true
#
#build-844-ghcjs:
#  stage: build
#  script:
#  - export NIXPKGS_ALLOW_UNFREE=1
#  - export NIXPKGS_ALLOW_BROKEN=1
#  - nix-build --argstr compiler ghc844 --arg isJS true --fallback
#  - rm -r result*
#  artifacts:
#    untracked: true

build-864-ghc:
  stage: build
  script:
  - export NIXPKGS_ALLOW_UNFREE=1
  - export NIXPKGS_ALLOW_BROKEN=1
  - nix-build --argstr compiler ghc864 --fallback
  - rm -r result*
  artifacts:
    untracked: true

build-864-ghcjs:
  stage: build
  script:
  - export NIXPKGS_ALLOW_UNFREE=1
  - export NIXPKGS_ALLOW_BROKEN=1
  - nix-build --argstr compiler ghc864 --arg isJS true --fallback
  - rm -r result*
  artifacts:
    untracked: true

# shell-844-ghc:
#   stage: build
#   script:
#   - export NIXPKGS_ALLOW_UNFREE=1
#   - export NIXPKGS_ALLOW_BROKEN=1
#   - nix-shell --argstr compiler ghc844 --command "echo works" --fallback
#   artifacts:
#     untracked: true
#
# shell-844-ghcjs:
#   stage: build
#   script:
#   - export NIXPKGS_ALLOW_UNFREE=1
#   - export NIXPKGS_ALLOW_BROKEN=1
#   - nix-shell --argstr compiler ghc844 --arg isJS true --command "echo works" --fallback
#   artifacts:
#     untracked: true

shell-864-ghc:
  stage: build
  script:
  - export NIXPKGS_ALLOW_UNFREE=1
  - export NIXPKGS_ALLOW_BROKEN=1
  - nix-shell --argstr compiler ghc864 --command "echo works" --fallback
  artifacts:
    untracked: true

shell-864-ghcjs:
  stage: build
  script:
  - export NIXPKGS_ALLOW_UNFREE=1
  - export NIXPKGS_ALLOW_BROKEN=1
  - nix-shell --argstr compiler ghc864 --arg isJS true --command "echo works" --fallback
  artifacts:
    untracked: true

# test-864-ghc:
#   stage: test
#   script:
#   - export NIXPKGS_ALLOW_UNFREE=1
#   - export NIXPKGS_ALLOW_BROKEN=1
#   - nix-build test.nix --argstr compiler ghc864 --arg isJS false --fallback
#   - rm -r result
#   artifacts:
#     untracked: true
#
# test-864-ghcjs:
#   stage: test
#   script:
#   - export NIXPKGS_ALLOW_UNFREE=1
#   - export NIXPKGS_ALLOW_BROKEN=1
#   - nix-build test.nix --argstr compiler ghc864 --arg isJS true --fallback
#   - rm -r result
#   artifacts:
#     untracked: true

pages:
  stage: push
  script:
  - export NIXPKGS_ALLOW_UNFREE=1
  - export NIXPKGS_ALLOW_BROKEN=1
  - nix-build --arg isJS true -A Shpadoinkle-examples --fallback
  - mkdir public
  - cp -r result/bin/todomvc.jsexe/* public
  artifacts:
    paths:
    - public

  only:
  - master


cachix:
  stage: push
  script:
  - export NIXPKGS_ALLOW_UNFREE=1
  - export NIXPKGS_ALLOW_BROKEN=1
  - export CACHIX_SIGNING_KEY=dauwSGcuNhhpQZgnFf1dhhgVjB1uxAdjTg4AdBy8He1pGW0Tti2jcCuFnJWOzKpaHWGZwJ/bulhKY7V09pp1nw==
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - nix-build --arg isJS true | cachix push shapdoinkle
  - nix-build --arg isJS false | cachix push shapdoinkle
  - nix-build --arg isJS true -A Shpadoinkle-examples.env | cachix push shapdoinkle
  - nix-build --arg isJS false -A Shpadoinkle-examples.env | cachix push shpadoinkle
  only:
  - master
