stages:
  - build

compile:
  stage: build
  script:
  - nix-build --argstr compiler ghc843
  - nix-build --argstr compiler ghcjs84
  artifacts:
    untracked: true

pages:
  stage: build
  script:
  - nix-build -A Shpadoinkle-examples
  - mkdir public
  - cp -r result/bin/todomvc.jsexe/* public
  artifacts:
    paths:
    - public

  only:
  - master

