= Getting Started


* xref:getting-started/extend-an-example.adoc[Extend an Example]
* xref:getting-started/adding-to-your-project.adoc[Adding to a Project]

Shpadoinkle is built with Nix, but you can build however you like. `stack` and `cabal` are supported with or without Nix.

[TIP]
.â›„
====
The fastest way to start a new Shpadoinkle project is to build a https://gitlab.com/fresheyeball/Shpadoinkle-snowman/-/tree/master#snowman[Snowman].
[source,bash]
----
bash <( curl https://gitlab.com/fresheyeball/Shpadoinkle-snowman/-/raw/master/generator.sh )
----
====

== Nix

Nix works on all Linux distributions, as well as Darwin-based operating systems such as MacOS. To install Nix run:

[source,bash]
----
curl -L https://nixos.org/nix/install | sh
----

[WARNING]
.ðŸ‘ Follow ðŸ‘ Instructions
The install script outputs important instructions you need to follow. Read the output and follow instructions.

Success is indicated by the presence of the Nix toolchain in your terminal...

[source,bash]
----
nix --version
----

[NOTE]
.MacOS
Installing Nix on MacOS should work fine, but if you end up in a sticky situation, https://medium.com/@robinbb/install-nix-on-macos-catalina-ca8c03a225fc[this article may help.] You can also refer to https://nixos.org/manual/nix/stable/#sect-macos-installation[the official manual] for more information about Nix.


== Cachix

Some of the work done with Nix includes deviations from the official Nix package set. As such, some dependencies are not cached on https://cache.nixos.org. Building these dependencies from source can be very slow. If you would like to avoid this wait, you can pull from our https://cachix.org/[Cachix] cache of pre-built dependencies.

[source,bash]
----
nix-env -iA cachix -f https://cachix.org/api/v1/install
cachix use shpadoinkle
----

Now builds of Shpadoinkle will used cached dependencies from https://shpadoinkle.cachix.org/[shpadoinkle.cachix.org], which are kept up to date with `master` using GitLab CI.
