name:         Shpadoinkle-backend-static
license:      BSD3
license-file: LICENSE
author:       Isaac Shapira
version:      0.1.0.2
maintainer:   fresheyeball@protonmail.com
category:     Web
build-type:   Simple
synopsis:     A backend for rendering Shpadoinkle as Text.
description:
  Shpadoinkle's static backend, renders Html as Text. Event listeners are ignored.
  This is useful when rendering on the server, or for static site generation.


ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
    - -fwarn-incomplete-uni-patterns
    - -fwarn-tabs
    - -fwarn-incomplete-record-updates
    - -fwarn-identities


extra-source-files:
  - README.md
  - CHANGELOG.md


dependencies:
    - base >= 4.12.0 && < 4.16


library:
  exposed-modules:
      Shpadoinkle.Backend.Static
  source-dirs: .
  dependencies:
    - compactable >= 0.1.2 && < 0.2
    - text        >= 1.2.3 && < 1.3

    - Shpadoinkle
