name:         Shpadoinkle-disembodied
license:      BSD3
license-file: LICENSE
author:       Isaac Shapira
version:      0.0.0.1
maintainer:   fresheyeball@protonmail.com
category:     Web
build-type:   Simple
synopsis:     Shpadoinkle as a static site.
description:
  Static site backed SPA applications.


ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
    - -fwarn-incomplete-uni-patterns
    - -fwarn-tabs
    - -fwarn-incomplete-record-updates
    - -fwarn-identities


extra-source-files:
  - README.md
  - CHANGELOG.md


dependencies:
    - base >= 4.12.0 && < 4.16


library:
  exposed-modules:
    - Shpadoinkle.Disembodied
  other-modules:
    - Shpadoinkle.Disembodied.Sample
  source-dirs: .
  dependencies:
    - directory
    - filepath
    - text        >= 1.2.3 && < 1.3
    - servant
    - unliftio

    - Shpadoinkle
    - Shpadoinkle-backend-static
    - Shpadoinkle-router
    - Shpadoinkle-html
