name:         Shpadoinkle
license:      BSD3
license-file: LICENSE
version:      0.1.1.0
author:       Isaac Shapira
maintainer:   fresheyeball@protonmail.com
category:     Web
build-type:   Simple
synopsis:     A programming model for declarative, high performance user interface.
description:
  Shpadoinkle is a programming model for user interface development. It supports flexible,
  simple, declarative code by modeling user interface interactions as Coalgebras.

  This package implements the bare-bones core abstraction. By performing little work
  shpadoinkle is trivially high performance.


ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
    - -fwarn-incomplete-uni-patterns
    - -fwarn-tabs
    - -fwarn-incomplete-record-updates
    - -fwarn-identities


extra-source-files:
  - README.md
  - CHANGELOG.md


dependencies:
    - base >= 4.12.0 && < 4.16


when:
  - condition: impl(ghcjs)
    then:
      dependencies: []
    else:
      dependencies:
        - jsaddle-warp >= 0.9.7 && < 0.20


library:
  source-dirs: .
  dependencies:
    - category  >= 0.2   && <0.3
    - jsaddle   >= 0.9.7 && < 0.20
    - text      >= 1.2.3 && < 1.3
    - unliftio

    - Shpadoinkle-continuations


git: https://gitlab.com/fresheyeball/Shpadoinkle.git
