name:         Shpadoinkle-widgets
license:      BSD3
license-file: LICENSE
version:      0.2.0.0
author:       Isaac Shapira
maintainer:   fresheyeball@protonmail.com
category:     Web
build-type:   Simple
synopsis:     A collection of common reusable types and components.
description:
  There are many shared abstractions between various UIs that represent
  themselves in frameworks and applications. This package provides a useful
  subset of these concepts as types along with implementations consuming
  these types.


flags:
  testing:
    description: Provide test kit around QuickCheck
    default:     False
    manual:      True


ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
    - -fwarn-incomplete-uni-patterns
    - -fwarn-tabs
    - -fwarn-incomplete-record-updates
    - -fwarn-identities


extra-source-files:
  - README.md
  - CHANGELOG.md


dependencies:
    - base >= 4.12.0 && < 4.16


library:
  exposed-modules:
    - Shpadoinkle.Widgets.Form.Input
    - Shpadoinkle.Widgets.Form.Dropdown
    - Shpadoinkle.Widgets.Table
    - Shpadoinkle.Widgets.Table.Lazy
    - Shpadoinkle.Widgets.Types
    - Shpadoinkle.Widgets.Types.Choice
    - Shpadoinkle.Widgets.Types.ConsideredChoice
    - Shpadoinkle.Widgets.Types.Core
    - Shpadoinkle.Widgets.Types.Form
    - Shpadoinkle.Widgets.Types.Physical
    - Shpadoinkle.Widgets.Types.Remote
    - Shpadoinkle.Widgets.Types.Search
    - Shpadoinkle.Widgets.Validation
  source-dirs: .
  dependencies:
    - jsaddle          >= 0.9.7 && < 0.20
    - aeson            >= 1.4.4 && < 1.6
    - containers       >= 0.6.0 && < 0.7
    - text             >= 1.2.3 && < 1.3
    - template-haskell >= 2.14.0 && < 2.17
    - mtl              >= 2.2.2 && < 2.3
    - stm              >= 2.5.0 && < 2.6
    - unliftio         >= 0.2.12 && < 0.3
    - compactable      >= 0.1.2 && < 0.2
    - edit-distance    >= 0.2.2 && < 0.3
    - email-validate   >= 2.3.2 && < 2.4

    - Shpadoinkle
    - Shpadoinkle-html
  when:
    - condition: flag(testing)
      then:
        exposed-modules:
          - Test.QuickCheck.Classes.Hspec
          - Test.QuickCheck.Classes.FoldableOrd
        cpp-options: -DTESTING
        dependencies:
          - transformers
          - QuickCheck
          - quickcheck-classes
          - quickcheck-classes-base
          - hspec
      else:
        cpp-options: []


tests:
  unit:
    cpp-options: -DTESTING
    source-dirs: tests
    main: Test.hs
    dependencies:
      - containers

      - QuickCheck
      - quickcheck-classes
      - quickcheck-classes-base
      - hspec

      - Shpadoinkle-widgets


git: https://gitlab.com/fresheyeball/Shpadoinkle.git
