= Tutorial

This is for those who would like to think they know precisely what they mean.

Skip to:

* xref:tutorial/calculator.adoc[Part 2, Simple Calculator ->]
* xref:tutorial/immediate-execution.adoc[Part 3, Immediate Execution ->]

== Setup

This project should work with any system capable of compiling code with https://www.haskell.org/ghc/[GHC]. However this project is built with Nix, and so that is what is recommended for the tutorial.

If you do not have Nix, please follow the instructions located xref:getting-started/index.adoc#Nix[here].

You will also need to clone the {snowman}[Snowman]. This is a minimal "Hello World" example repo where you can build a Shpadoinkle application.

[source,bash]
----
curl -L https://nixos.org/nix/install | sh
# Follow the instructions printed by the above command
nix --version
nix-env -iA cachix -f https://cachix.org/api/v1/install
cachix use shpadoinkle
git clone https://gitlab.com/fresheyeball/Shpadoinkle-snowman.git
cd Shpadoinkle-snowman
nix-shell
----

Now you should be setup with a development environment. Sandard `cabal` toolchain should work out of the box, as well as `ghcid`.

[CAUTION]
.MacOS
If you are on MacOS instead of Linux, the Cachix cache will not work, as cross compilation has not been implimented on this project. Therefore getting a development environment with `nix-shell` is going to compile all the dependencies from source. This can take a long time.

== Basics

Shpadoinkle applications are represented a function from a given application state, to HTML that produces a new state of the same type. This function becomes something of a loop with itself, where each produced update to the state is applied to the same application to obtain new HTML which in turn can produce a new update.

Event handlers can be pure updates, or asynchronous updates. All updates that perform IO are considered asynchronous. This difference is tracked in the type system.

[source,haskell]
----
Prop a :: Type
----

For non-Monadic computations, that can immediately update the UI.

[source,haskell]
----
PropM m a :: Type
----

For Monadic computations that are expected to take some time to complete before there is an update for the UI.

This difference propagates to the Html types with

[source,haskell]
----
Html a :: Type
HtmlM m a :: Type
----

types respectively. Non-Monadic terms can be converted to Monadic terms by use of the injective function `constly`, however Monadic terms *cannot* be converted into Non-Monadic ones.

== Html

Shpadoinkle Html, is an opt in module for generating Shpadoinkle Core's Html types.

Each Html tag has named functions, including a plain version that accepts properties `[(Text, Prop a)]` and children `[Html a]`. Adding an underscore allows you to pass no properties. Adding a prime allows you to pass no children.

[source,haskell]
----
h1 [ id' "foo" ] [ text "bar" ]
----

will render as

[source,html]
----
<h1 id="foo" >bar</h1>
----

Text nodes being extremely common, have an extra overloaded API.

[source,haskell]
----
h1 [ id' "foo" ] [ "bar" ]
----

will work as well. Provided you have enabled `OverloadedStrings`.

=== CSS Classes

Due to the frequency of use, CSS classes have a polymorphic overloaded API. This includes multiple representations, all of which become `ClassList`. Which is just a `newtype` of `Set Text`.

To learn more about the html package see docs xref:packages/html.adoc[here].

=== Events

Event handling is achieved through properties. There are several named functions for each event type and a few additional helpers. A plain version for pure handlers, and an M version for Monadic ones. The plain version is polymorphic and will work with both `Prop` and `PropM` types, as where the Monadic version necessitates `PropM`.

[source,javascript]
----
const div = document.createElement("div")
div.addEventListener("click", doit)
----

is morally equivalent to

[source,haskell]
----
div' [ onClick doit ]
----

'''

Next we will use these concepts to build a calculator, in part 2.

xref:tutorial/calculator.adoc[Go to part 2: Simple calculator ->]


