= Tutorial

This is for those who would like to think they know precisely what they mean.

Skip to:

* xref:tutorial/calculator.adoc[Part 2, Simple Calculator ->]
* xref:tutorial/immediate-execution.adoc[Part 3, Immediate Execution ->]

== Setup

To begin, complete the setup described in the
xref:getting-started/index.adoc[Getting Started] section.

== Html

Shpadoinkle Html is an optional module for generating Shpadoinkle Core's Html types.

Each Html tag has named functions, including a plain version that accepts properties `[(Text, Prop a)]` and children `[Html a]`. Adding an underscore allows you to pass no properties. Adding a prime allows you to pass no children.

[source,haskell]
----
h1 [ id' "foo" ] [ text "bar" ]
----

will render as

[source,html]
----
<h1 id="foo" >bar</h1>
----

Text nodes, being extremely common, have an extra overloaded API.

[source,haskell]
----
h1 [ id' "foo" ] [ "bar" ]
----

will work as well. Provided you have enabled `OverloadedStrings`.

=== CSS Classes

Due to the frequency of use, CSS classes have a polymorphic overloaded API. This includes multiple representations, all of which become `ClassList`, which is just a `newtype` of `Set Text`.

To learn more about the HTML package see docs xref:packages/html.adoc[here].

=== Events

Event handling is achieved through properties. There are several named functions for each event type and a few additional helpers. A plain version for pure handlers, an M version for monadic handlers, and a C version for working with `Continuation`s.

[source,javascript]
----
const div = document.createElement("div")
div.addEventListener("click", doit)
----

is morally equivalent to

[source,haskell]
----
div' [ onClick doit ]
----

'''

Next we will use these concepts to build a calculator, in part 2.

xref:tutorial/calculator.adoc[Go to part 2: Simple calculator ->]
