= Html

This package exposes a template haskell generated DSL of HTML tags, as well as properties. While not complete, this package is intended to eventually house utilities for web apis.

== Named Tags

HTML tags each get **4** named functions, with the following semantic

[%header]
|===
| Variant | Properties Required | Children Required
| Plain | icon:check[] | icon:check[]
| Prime | icon:check[] | icon:times[]
| Underscore | icon:times[] | icon:check[]
| Prime + Underscore | icon:times[] | icon:times[]
|===

or we can see the semantic as follows

[source,haskell]
----
x [] = x'
flip x [] = x_
x [] [] = x'_
h "x" = x
----

We also supply some overload strings for convenience.

[source,haskell]
----
div "foo" [ "hiya" ]
> <div class="foo">hiya</div>
----

== Event Listeners

Event listeners each get **2** named functions. A plain one, for pure event handlers, and a prime version for Monadic handlers.

[source,haskell]
----
onX' (pure x) = onX x
----

Each of these functions is named the same way they are in JavaScript (sans Camel-case). IE the following are morally equivalent:

[source,javascript]
----
div.addEventListener("click", () => model++);
----

[source,haskell]
----
div' [ onClick (model + 1) ]
----

== Properties

Instead of orienting around attributes, we orient around _properties_ in Shpadoinkle. This is because, largely you can set any attribute by properties, but not vice versa. Credit due to https://kriszyp.github.io/alkali/[alkali] which introduced me to this observation.

In most cases the named function will have the same name it would have in JavaScript. For example the following are morally equivalent.

[source,javascript]
----
const div = document.createElement("div");
div.className = "foo";
----

[source,haskell]
----
div' [ className "foo" ]
----

