= Project Structure

Shpadoinkle is broken up into several modules that compose together or can be used separately.

xref:project-structure/core.adoc[Core] (https://gitlab.com/fresheyeball/Shpadoinkle/-/tree/master/core[Gitlab], https://hackage.haskell.org/package/Shpadoinkle[Hackage])::
This stores the core types and logic for Shpadoinkle. At minimum you need to have core and a backend to run an application.

xref:project-structure/html.adoc[Html] (https://gitlab.com/fresheyeball/Shpadoinkle/-/tree/master/html[Gitlab], https://hackage.haskell.org/package/Shpadoinkle-html[Hackage])::
A Template generated DSL defining HTML tags, Properties, and Events. It includes some related Utilities like Keyboard support.

xref:project-structure/backends.adoc[Static Backend] (https://gitlab.com/fresheyeball/Shpadoinkle/-/tree/master/backends/static[Gitlab], https://hackage.haskell.org/package/Shpadoinkle-backend-static[Hackage])::
Takes Shpadoinkle Html and renders it as a static HTML string.

xref:project-structure/backends.adoc[ParDiff Backend] (https://gitlab.com/fresheyeball/Shpadoinkle/-/tree/master/backends/pardiff[Gitlab], https://hackage.haskell.org/package/Shpadoinkle-backend-pardiff[Hackage])::
Canonical Virtual DOM written in Haskell based on Alignable Functors.

xref:project-structure/backends.adoc[Snabbdom Backend] (https://gitlab.com/fresheyeball/Shpadoinkle/-/tree/master/backends/snabbdom[Gitlab], https://hackage.haskell.org/package/Shpadoinkle-backend-snabbdom[Hackage])::
Binding to the high performance Snabbdom.js Virtual DOM library written in JavaScript.

xref:project-structure/router.adoc[Router] (https://gitlab.com/fresheyeball/Shpadoinkle/-/tree/master/router[Gitlab], https://hackage.haskell.org/package/Shpadoinkle-router[Hackage])::
SPA (Single Page Application) router based on https://docs.servant.dev/en/stable/[Servant].

xref:project-structure/widgets.adoc[Widgets] (https://gitlab.com/fresheyeball/Shpadoinkle/-/tree/master/widgets[Gitlab], https://hackage.haskell.org/package/Shpadoinkle-widgets[Hackage])::
Logical types and structures for common UI components, along with batteries included implementations.

Lens (https://gitlab.com/fresheyeball/Shpadoinkle/-/tree/master/lens[Gitlab])::
Lens combinators for ergonomic composing of heterogeneous components, and after-the-fact modification of views.

Examples (https://gitlab.com/fresheyeball/Shpadoinkle/-/tree/master/examples[Gitlab])::
Small applications of Shpadoinkle to illustrate programming patterns.

Experiments (https://gitlab.com/fresheyeball/Shpadoinkle/-/tree/master/experiments[Gitlab])::
Sandbox for exploring the territory.
