name:         Shpadoinkle-examples
license:      BSD3
license-file: LICENSE
version:      0.0.0.1
author:       Isaac Shapira
maintainer:   fresheyeball@protonmail.com
category:     Web
build-type:   Simple


ghc-options:
    - -Wall
    - -Werror
    - -Wcompat
    - -fwarn-redundant-constraints
    - -fwarn-incomplete-uni-patterns
    - -fwarn-tabs
    - -fwarn-incomplete-record-updates
    - -fwarn-identities


ghcjs-options:
    - -Wall
    - -Werror
    - -Wcompat
    - -fno-warn-missing-home-modules
    - -fwarn-redundant-constraints
    - -fwarn-incomplete-uni-patterns
    - -fwarn-tabs
    - -fwarn-incomplete-record-updates
    - -fwarn-identities
    - -dedupe


dependencies:
    - base


executables:
  todomvc:
    main: TODOMVC.hs
    other-modules:
      - TODOMVC.Types
      - TODOMVC.Update
    source-dirs: .
    when:
      - condition: impl(ghcjs)
        then:
          dependencies: []
        else:
          dependencies:
            - jsaddle-warp
    dependencies:
      - text
      - containers

      - Shpadoinkle
      - Shpadoinkle-html
      - Shpadoinkle-backend-pardiff

  todomvc-lens:
    main: TODOMVC_Lens.hs
    other-modules:
      - TODOMVC.Types
      - TODOMVC.Update
    source-dirs: .
    dependencies:
      - text
      - containers

      - mtl
      - lens
      - stm

      - Shpadoinkle
      - Shpadoinkle-html
      - Shpadoinkle-backend-pardiff

  counter:
    main: Counter.hs
    other-modules: []
    source-dirs: .
    dependencies:
      - text
      - stm

      - Shpadoinkle
      - Shpadoinkle-html
      - Shpadoinkle-backend-pardiff
