name:         Shpadoinkle-examples
license:      BSD3
license-file: LICENSE
version:      0.0.0.1
author:       Isaac Shapira
maintainer:   fresheyeball@protonmail.com
category:     Web
build-type:   Simple


ghc-options:
    - -Wall
    - -Werror
    - -Wcompat
    - -fwarn-redundant-constraints
    - -fwarn-incomplete-uni-patterns
    - -fwarn-tabs
    - -fwarn-incomplete-record-updates
    - -fwarn-identities


ghcjs-options:
    - -Wall
    - -Werror
    - -Wcompat
    - -fno-warn-missing-home-modules
    - -fwarn-redundant-constraints
    - -fwarn-incomplete-uni-patterns
    - -fwarn-tabs
    - -fwarn-incomplete-record-updates
    - -fwarn-identities
    - -dedupe


dependencies:
    - base

when:
  - condition: impl(ghcjs)
    then:
      dependencies: []
    else:
      dependencies:
        - jsaddle-warp

executables:
  todomvcatomic:
    main: TODOMVCAtomic.hs
    other-modules:
      - TODOMVCAtomic.Types
      - TODOMVCAtomic.Update
    source-dirs: .
    dependencies:
      - text
      - containers
      - lens

      - Shpadoinkle
      - Shpadoinkle-html
      - Shpadoinkle-backend-snabbdom

  todomvc:
    main: TODOMVC.hs
    other-modules:
      - TODOMVC.Types
      - TODOMVC.Update
    source-dirs: .
    dependencies:
      - text
      - containers

      - Shpadoinkle
      - Shpadoinkle-html
      - Shpadoinkle-backend-pardiff

  counter:
    main: Counter.hs
    other-modules: []
    source-dirs: .
    dependencies:
      - text
      - stm

      - Shpadoinkle
      - Shpadoinkle-html
      - Shpadoinkle-backend-pardiff

  widgets:
    main: Widgets.hs
    source-dirs: ./widgets
    dependencies:
      - text
      - stm

      - Shpadoinkle
      - Shpadoinkle-backend-pardiff
      - Shpadoinkle-html
      - Shpadoinkle-widgets

  servant-crud-client:
    main: Client.hs
    source-dirs: ./servant-crud
    other-modules:
      - Types
    dependencies:
      - aeson
      - lens
      - text
      - stm
      - containers
      - servant
      - polysemy

      - Shpadoinkle
      - Shpadoinkle-backend-pardiff
      - Shpadoinkle-html
      - Shpadoinkle-widgets
      - Shpadoinkle-router
    when:
      - condition: impl(ghcjs)
        then:
          dependencies:
            - servant-client-ghcjs
        else:
          dependencies:
            - servant-client

  servant-crud-server:
    main: Server.hs
    source-dirs: ./servant-crud
    other-modules:
      - Types
    dependencies:
      - aeson
      - text
      - lens
      - stm
      - containers
      - servant
      - polysemy

      - Shpadoinkle
      - Shpadoinkle-backend-pardiff
      - Shpadoinkle-html
      - Shpadoinkle-widgets

