:relfilesuffix: /
:relfileprefix: /
:icons: font

_This is for those who would like to think they know precisely what they mean._

* xref:tutorial/calculator.adoc[Part 2, Simple Calculator ->]

== Setup

To begin, complete the setup described in the
xref:getting-started.adoc[Getting Started] section.

== HTML

We begin by exploring html generation in Shpadoinkle.

`Shpadoinkle Html` is an optional module for generating HTML. Here's how it
works.

Each HTML tag has an associated named function. For the `H1` HTML tag, for
example:

[source,haskell]
----
h1 [ id' "foo" ] [ text "bar" ]
----

will render as

[source,html]
----
<h1 id="foo" >bar</h1>
----

Each HTML tag's associated function accepts 2 arguments: first, a list of the
properties (of type `[(Text, Prop m a)]`); and second, a list of the children
HTML tags (of type `[Html m a]`).

Each such named function has 2 additonal versions. Appending an underscore to
the named function gives a version of the function that takes no properties.
For example:

[source,haskell]
----
h1_ [ text "bar" ]
----

will render as

[source,html]
----
<h1>bar</h1>
----

Appending a prime to the named function gives a version of the function
that takes no children. For example:

[source,haskell]
----
div' [ id' "mydiv" ]
----

will render as

[source,html]
----
<div id="mydiv" ></div>
----

Text nodes, being extremely common, can be used directly as HTML tags provided
you have enabled the `OverloadedStrings` compiler pragma. Example:

[source,haskell]
----
h1 [ id' "foo" ] [ "bar" ]
----

will render as

[source,html]
----
<h1 id="foo" >bar</h1>
----

(Notice the lack of `text "bar"`.)

=== CSS Classes

This is by **far** the most common property to set. Extra affordances are
offered. These 3 expressions:

[source,haskell]
----
div' "foo bar"
div' [ class' "foo bar" ]
div' [ class' ["foo", "bar"] ]
----

will *each* render as:

[source,html]
----
<div class="foo bar" ></div>
----

To learn more about the `Shpadoinkle Html` package, see
xref:packages/html.adoc[the docs].

=== Events

Event handlers are properties. Event handling is achieved by attaching event
handlers as propoprties of HTML elements. There are several named functions for
each event type and a few additional helpers.

This JavaScript code

[source,javascript]
----
const div = document.createElement("div")
div.addEventListener("click", doit)
----

is obtained from this Shpadoinkle Haskell code:

[source,haskell]
----
div' [ onClick doit ]
----

Next, we will use these concepts to build a calculator.

xref:tutorial/calculator.adoc[Tutorial Part 2: Simple calculator ->]
