name:         Shpadoinkle-streaming
license:      BSD3
license-file: LICENSE
version:      0.0.0.1
author:       Morgan Thomas
maintainer:   morgan.a.s.thomas@gmail.com
category:     Web
build-type:   Simple
synopsis:     Integration of the streaming library with Shpadoinkle continuations.
description:
  Integration of the streaming library with Shpadoinkle continuations.


ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
    - -fwarn-tabs
    - -fwarn-incomplete-record-updates
    - -fwarn-identities


dependencies:
    - base >= 4.12.0 && < 4.16
    - lens
    - streaming >= 0.2 && < 0.3
    - text

    - Shpadoinkle


library:
  exposed-modules: Shpadoinkle.Streaming
  source-dirs: .
