name:         Shpadoinkle-backend-pardiff
license:      BSD3
license-file: LICENSE
author:       Isaac Shapira
version:      0.0.0.1
maintainer:   fresheyeball@protonmail.com
category:     Web
build-type:   Simple


ghc-options:
    - -Wall
    - -Werror
    - -Wcompat
    - -fwarn-redundant-constraints
    - -fwarn-incomplete-uni-patterns
    - -fwarn-tabs
    - -fwarn-incomplete-record-updates
    - -fwarn-identities


dependencies:
    - base


library:
  other-modules: Data.Once
  exposed-modules:
      Shpadoinkle.Backend.ParDiff
  source-dirs: .
  dependencies:
    - jsaddle
    - unliftio
    - compactable
    - uuid
    - neat-interpolation
    - containers
    - semialign
    - these
    - lens
    - random
    - text

    - mtl
    - file-embed

    - Shpadoinkle

when:

  - condition: impl(ghcjs)
    then:
      dependencies: []
    else:
      dependencies:
        - jsaddle-warp

