name:         Shpadoinkle-backend-pardiff
license:      BSD3
license-file: LICENSE
author:       Isaac Shapira
version:      0.3.0.0
maintainer:   fresheyeball@protonmail.com
category:     Web
build-type:   Simple
synopsis:     A Virtual Dom in pure Haskell, based on Html as an Alignable Functor.
description:
  Virtual DOM diffing in pure Haskell. The diffing is a lawful usage of @alignWith@
  from the @Data.These@ package. This implementation stores a reference to the @RawNode@
  for each node in the virtual tree, merging keyed and unkeyed virtual DOM techniques.


ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
    - -fwarn-incomplete-uni-patterns
    - -fwarn-tabs
    - -fwarn-incomplete-record-updates
    - -fwarn-identities


extra-source-files:
  - README.md
  - CHANGELOG.md


dependencies:
    - base >= 4.12.0 && < 4.16


library:
  other-modules: Data.Once
  exposed-modules:
      Shpadoinkle.Backend.ParDiff
  source-dirs: .
  dependencies:
    - jsaddle              >= 0.9.7 && < 0.20
    - ghcjs-dom            >= 0.9.4 && < 0.20
    - containers           >= 0.6.0 && < 0.7
    - exceptions
    - text                 >= 1.2.3 && < 1.3
    - random               >= 1.1 && < 1.3
    - monad-control        >= 1.0.2 && < 1.1
    - mtl                  >= 2.2.2 && < 2.3
    - unliftio             >= 0.2.12 && < 0.3
    - compactable          >= 0.1.2 && < 0.2
    - file-embed           >= 0.0.11 && < 0.1
    - transformers-base    >= 0.4.5 && < 0.5

    - Shpadoinkle


git: https://gitlab.com/platonic/shpadoinkle.git
