name:         Shpadoinkle-html
license:      BSD3
license-file: LICENSE
version:      0.1.1.0
author:       Isaac Shapira
maintainer:   fresheyeball@protonmail.com
category:     Web
build-type:   Simple
synopsis:     A typed, template generated Html DSL, and helpers.
description:
  Shpadoinkle Html is a typed template generated Html DSL building on
  types provided by Shpadoinkle Core. This exports a large namespace
  of terms covering most of the Html specifications. Some Elm API
  style helpers are present but as outlaw type classes.


ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
    - -fwarn-incomplete-uni-patterns
    - -fwarn-tabs
    - -fwarn-incomplete-record-updates
    - -fwarn-identities


extra-source-files:
  - README.md
  - CHANGELOG.md


dependencies:
    - base >= 4.12.0 && < 4.16
    - bytestring
    - containers       >= 0.6.0 && < 0.7
    - compactable
    - text             >= 1.2.3 && < 1.3
    - time
    - template-haskell >= 2.14.0 && < 2.17
    - stm              >= 2.5.0 && < 2.6
    - unliftio
    - ghcjs-dom
    - jsaddle          >= 0.9.7 && < 0.20
    - jsaddle-dom

    - Shpadoinkle      >= 0.1 && < 0.2


when:
  - condition: impl(ghcjs)
    then:
      dependencies:
        - ghcjs-base
    else:
      dependencies:
        - regex-pcre

library:
  exposed-modules:
    - Shpadoinkle.Html
    - Shpadoinkle.Html.Element
    - Shpadoinkle.Html.Event
    - Shpadoinkle.Html.Property
    - Shpadoinkle.Html.Memo
    - Shpadoinkle.Html.MicroData
    - Shpadoinkle.Html.Utils
    - Shpadoinkle.Html.LocalStorage
    - Shpadoinkle.Html.TH
    - Shpadoinkle.Html.TH.CSS
    - Shpadoinkle.Keyboard
  source-dirs: .


git: https://gitlab.com/fresheyeball/Shpadoinkle.git
