name:         Shpadoinkle-html
license:      BSD3
license-file: LICENSE
version:      0.0.0.1
author:       Isaac Shapira
maintainer:   fresheyeball@protonmail.com
category:     Web
build-type:   Simple


ghc-options:
    - -Wall
    - -Werror
    - -Wcompat
    - -fwarn-redundant-constraints
    - -fwarn-incomplete-uni-patterns
    - -fwarn-tabs
    - -fwarn-incomplete-record-updates
    - -fwarn-identities


dependencies:
    - base


library:
  exposed-modules:
    - Shpadoinkle.Html
    - Shpadoinkle.Html.Memo
    - Shpadoinkle.Html.Utils
    - Shpadoinkle.Html.LocalStorage
    - Shpadoinkle.Keyboard
  source-dirs: .
  dependencies:
    - jsaddle
    - text
    - template-haskell
    - containers
    - stm
    - unliftio

    - Shpadoinkle
